# Individual Project 2
## by Eli Dalton
### version: 1.0
### CS-160-Introduction to Data Science
### Spring 2023

## Working with NumPy

In [1]:
import numpy as np

In [3]:
# Create a 2-by-2 NumPy array with elements 10,20,30,40 in it

In [4]:
x1 = np.array([[10,20], [30,40]])
print(x1)

[[10 20]
 [30 40]]


In [5]:
# Then use broadcasting to perform each of the following operations:

In [6]:
# i. Square every element of the array.

np.power(x1, 2)

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

In [7]:
# ii. Add 100 to every element of the array.

x1 + 100

array([[110, 120],
       [130, 140]])

In [8]:
# iii. Multiply every element of the array by 5.

x1*5

array([[ 50, 100],
       [150, 200]])

In [9]:
# iv. Calculate the square root of each element in the array.

np.power(x1, 0.5)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [10]:
# Create a 3-by-5 array containing integers from 3 to 27 in multiples of 3.

In [38]:
x2 = np.array([[6,12,3,18,27],[9,15,12,24,21],[3,18,12,27,9]])
x2

array([[ 6, 12,  3, 18, 27],
       [ 9, 15, 12, 24, 21],
       [ 3, 18, 12, 27,  9]])

In [12]:
# Create a second 3-by-3 array with 9 elements evenly spaced between 10 and 20.

In [29]:
x3 = np.linspace(10,20, 9)
x3.resize(3,3)
print(x3)

[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]


In [39]:
# Multiply these arrays together and display the output.

In [40]:
x2 * x3

ValueError: operands could not be broadcast together with shapes (3,5) (3,3) 

In [41]:
#Attached to the assignment are five .npy files that contain five values each. Read these files in and stack them into a
#unified dataset. This would be a 5-by-5 NumPy array. Then clacluate the mean of each column of data. Let Python do all
#of the heavy liftins!

In [42]:
x4 = np.load("process1.npy")
x5 = np.load("process2.npy")
x6 = np.load("process3.npy")
x7 = np.load("process4.npy")
x8 = np.load("process5.npy")

In [43]:
x9 = np.vstack([x4,x5,x6,x7,x8])
x9

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [44]:
np.mean(x9, axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])